mod aliagn_avx;
mod amortized_packed;
mod blas_blocked;
mod cache_tuned;
mod jit_ultimate;
mod naive;
mod parallel;
mod parallel_pack_scale;
mod parallel_packed;
mod pipeline_unroll;
mod pipelined_avx;
mod prefetched_ultimate;
mod register_16;
mod register_direct;
mod register_scale;
mod reordered;
mod tiled;
mod tiled_packed;
mod tiled_parallel;
mod tiled_register;
mod tiled_simd;

pub use aliagn_avx::matmul_aligned_avx;
pub use amortized_packed::matmul_amortized_packed;
pub use blas_blocked::matmul_blas_blocked;
pub use cache_tuned::matmul_cache_tuned;
pub use jit_ultimate::matmul_jit_ultimate;
pub use naive::matmul_naive;
pub use parallel::matmul_parallel;
pub use parallel_pack_scale::matmul_parallel_pack_scale;
pub use parallel_packed::matmul_parallel_packed;
pub use pipeline_unroll::matmul_pipeline_unroll;
pub use pipelined_avx::matmul_pipelined_avx;
pub use prefetched_ultimate::matmul_prefetched_ultimate;
pub use register_16::matmul_register_16;
pub use register_direct::matmul_register_direct;
pub use register_scale::matmul_register_scale;
pub use reordered::matmul_reordered;
pub use tiled::matmul_tiled;
pub use tiled_packed::matmul_tiled_packed;
pub use tiled_parallel::matmul_tiled_parallel;
pub use tiled_register::matmul_tiled_register;
pub use tiled_simd::matmul_tiled_simd;
